Repository doocs/leetcode, pull requests merged in 2018-10, with the labels that each got.

#16 Add solution 001 [golang][scala]
  solution/001.Two Sum/Solution.go
  solution/001.Two Sum/Solution.scala
Labels: question

#18 Solution2.py
  solution/001.Two Sum/Solution2.py
Labels: good first issue

#42 Add Solution 027[Java]
  solution/025.Reverse Nodes in k-Group/README.md
  solution/025.Reverse Nodes in k-Group/Solution.java
  solution/026.Remove Duplicates from Sorted Array/README.md
  solution/026.Remove Duplicates from Sorted Array/Solution.java
  solution/027.Remove Element/README.md
  solution/027.Remove Element/Solution.java
Labels: good first issue

#45 update solution 002 Solution.js [JavaScript]
  solution/002.Add Two Numbers/Solution.js
Labels: need optimization

#50 add solution 146 with java
  solution/146.Lru Cache/README.md
  solution/146.Lru Cache/Solution.java
Labels: need optimization

#60 6. ZigZag Conversion (java)
  solution/006.ZigZag Conversion/Solution.java
Labels: good first issue

#67 Update solution 014 [Python2]-20ms
  Solution2.py
  solution/001.Two Sum/Solution2.py
  solution/007.Reverse Integer/Solution2.py
  solution/013.Roman to Integer/Solution2.py
Labels: good first issue
