Repository doocs/leetcode, pull requests merged in 2018-12, with the labels that each got.

#132 add solution 0952
  img/Largest-Component-Size-by-Common-Factor1.png
  img/Largest-Component-Size-by-Common-Factor2.png
  img/Largest-Component-Size-by-Common-Factor3.png
  solution/0952.Largest Component Size by Common Factor/README.md
  solution/0952.Largest Component Size by Common Factor/Solution.java
Labels: need optimization

#134 add 0953 folder & cpp(4ms) version
  solution/0953.Verifying an Alien Dictionary/Solution.cpp
Labels: good issue

#135 update solution
  solution/0001.Two Sum/Solution3.js
  solution/0002.Add Two Numbers/Solution2.js
  solution/0003.Longest Substring Without Repeating Characters/Solution.js
Labels: good first issue
