Repository doocs/leetcode, pull requests merged in 2018-11, with the labels that each got.

#79 009 Palindrome Number - Python
  solution/009.Palindrome Number/Solution.py
Labels: need optimization

#98 0605 Can Place Flowers - Python
  solution/0605.Can Place Flowers/Solution.py
Labels: bug

#99 Add Solution 123[CPP]
  solution/0012.Integer to Roman/Solution.java
  solution/0018.4Sum/Solution.cpp
  solution/0031.Next Permutation/Solution.cpp
  solution/0042.Trapping Rain Water/README.md
  solution/0042.Trapping Rain Water/Solution.cpp
  solution/0123.Best Time to Buy and Sell Stock III/README.md
  solution/0123.Best Time to Buy and Sell Stock III/Solution.cpp
  solution/0448.Find All Numbers Disappeared in an Array/README.md
  solution/0448.Find All Numbers Disappeared in an Array/Solution.cpp
Labels: conflict, invalid

#108 0054 Spiral Matrix - Python
  solution/0054.Spiral Matrix/Solution.py
Labels: good issue

#114 0041 First Missing Positive - Python
  solution/0041.First Missing Positive/Solution.py
Labels: good issue

#115 0200.Number of Islands-python
  solution/0200.Number of Islands/README.md
  solution/0200.Number of Islands/Solution.py
  solution/0789.Escape The Ghosts/README.md
  solution/0789.Escape The Ghosts/Solution.py
Labels: good issue

#116 add the solution of 0889.
  solution/0889.Construct Binary Tree from Preorder and Postorder Traversal/README.md
  solution/0889.Construct Binary Tree from Preorder and Postorder Traversal/Solution.py
Labels: good issue

#120 add solution of 0670-python
  solution/0670.Maximum Swap/README.md
  solution/0670.Maximum Swap/Solution.py
Labels: good issue

#125 0190 Reverse Bits - Python
  solution/0190.Reverse Bits/Solution.py
Labels: good issue

#127 0073 Set Matrix Zeroes - Python
  solution/0073.Set Matrix Zeroes/Solution.py
  solution/0074.Search a 2D Matrix/Solution.py
Labels: good issue
