Repository doocs/leetcode, pull requests merged in 2025-04, with the labels that each got.

#4369 chore: update workflow
  .github/workflows/deploy.yml
Labels: core team, yml

#4370 feat: update solution to lc problem: No.2799
  solution/2700-2799/2799.Count Complete Subarrays in an Array/README.md
  solution/2700-2799/2799.Count Complete Subarrays in an Array/README_EN.md
  solution/2700-2799/2799.Count Complete Subarrays in an Array/Solution.rs
  solution/2700-2799/2799.Count Complete Subarrays in an Array/Solution2.rs
Labels: md, rs, core team

#4371 feat: add rust solution to lc problem: No.2845
  solution/2800-2899/2845.Count of Interesting Subarrays/README.md
  solution/2800-2899/2845.Count of Interesting Subarrays/README_EN.md
  solution/2800-2899/2845.Count of Interesting Subarrays/Solution.rs
Labels: md, rs, core team

#4373 feat: update solutions to lc problem: No.2444
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/README.md
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/README_EN.md
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/Solution.c
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/Solution.cpp
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/Solution.rs
  solution/2400-2499/2444.Count Subarrays With Fixed Bounds/Solution.ts
Labels: md, ts, cpp, rs, core team, c

#4375 feat: add rust solution to lc problem: No.3392
  solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/README.md
  solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/README_EN.md
  solution/3300-3399/3392.Count Subarrays of Length Three With a Condition/Solution.rs
Labels: md, rs, core team

#4376 docs: add deepwiki badge
  README.md
  README_EN.md
Labels: md, core team

#4377 feat: add rust solution to lc problem: No.2300
  solution/2300-2399/2300.Successful Pairs of Spells and Potions/README.md
  solution/2300-2399/2300.Successful Pairs of Spells and Potions/README_EN.md
  solution/2300-2399/2300.Successful Pairs of Spells and Potions/Solution.rs
Labels: md, rs, core team

#4378 feat: add solutions to lc problem: No.1295
  solution/1200-1299/1295.Find Numbers with Even Number of Digits/README.md
  solution/1200-1299/1295.Find Numbers with Even Number of Digits/README_EN.md
  solution/1200-1299/1295.Find Numbers with Even Number of Digits/Solution.rs
  solution/1200-1299/1295.Find Numbers with Even Number of Digits/Soluton.cs
Labels: md, rs, core team, cs

#4380 feat: add solutions to lc problem: No.3528
  solution/3500-3599/3528.Unit Conversion I/README.md
  solution/3500-3599/3528.Unit Conversion I/README_EN.md
  solution/3500-3599/3528.Unit Conversion I/Solution.cpp
  solution/3500-3599/3528.Unit Conversion I/Solution.go
  solution/3500-3599/3528.Unit Conversion I/Solution.java
  solution/3500-3599/3528.Unit Conversion I/Solution.py
  solution/3500-3599/3528.Unit Conversion I/Solution.ts
Labels: md, ts, py, go, java, cpp, core team
